### ISSUE TITLE
Update Maven repository

### ISSUE THREAD

**Issue by erhenjt** [tukaani-project/xz-java#16]
The latest version of xz-java on Maven central/Sonatype is 1.9, which was released more than three years ago and hasn't been updated since. Is there any plan to release a new version?

**Comment by Larhzu** [comment]
Yes. I happen to be a bit busy for certain reasons for now though.

There are two branches that likely are close to ready to be merged.
Perhaps minor tweaks are needed, we'll see. I don't think 1.10 needs
much else than these things. It doesn't add much but it's still
something; there hasn't been much development in the past three years.
